### ISSUE TITLE
Issue regarding RabbitMQ (Failed to convert message)

### ISSUE THREAD

**Issue by SaiSrujanEmula** [mechero/spring-boot-amqp-messaging#11]
hey could you please help me in fixing the issue

I am facing this after updating spring boot to 3.1.2 version

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] 2023-08-23T10:48:42.446Z WARN 7 --- [rmonyconsumer-1] s.a.r.l.ConditionalRejectingErrorHandler : Execution of Rabbit message listener failed.

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] org.springframework.amqp.rabbit.support.ListenerExecutionFailedException: Failed to convert message

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:158) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1660) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1579) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1567) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1558) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListenerAndHandleException(AbstractMessageListenerContainer.java:1503) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.lambda$executeListener$8(AbstractMessageListenerContainer.java:1481) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at io.micrometer.observation.Observation.lambda$observe$0(Observation.java:493) ~[micrometer-observation-1.11.2.jar:1.11.2]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at io.micrometer.observation.Observation.observeWithContext(Observation.java:603) ~[micrometer-observation-1.11.2.jar:1.11.2]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at io.micrometer.observation.Observation.observe(Observation.java:492) ~[micrometer-observation-1.11.2.jar:1.11.2]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1481) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:994) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:941) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1323) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1225) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] Caused by: org.springframework.amqp.support.converter.MessageConversionException: Failed to convert Message content

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.support.converter.AbstractJackson2MessageConverter.doFromMessage(AbstractJackson2MessageConverter.java:367) ~[spring-amqp-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.support.converter.AbstractJackson2MessageConverter.fromMessage(AbstractJackson2MessageConverter.java:321) ~[spring-amqp-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.support.converter.AbstractJackson2MessageConverter.fromMessage(AbstractJackson2MessageConverter.java:304) ~[spring-amqp-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.adapter.AbstractAdaptableMessageListener.extractMessage(AbstractAdaptableMessageListener.java:342) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter$MessagingMessageConverterAdapter.extractPayload(MessagingMessageListenerAdapter.java:385) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.support.converter.MessagingMessageConverter.fromMessage(MessagingMessageConverter.java:132) ~[spring-amqp-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.toMessagingMessage(MessagingMessageListenerAdapter.java:258) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:148) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] ... 15 common frames omitted

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] Caused by: java.io.UnsupportedEncodingException: 1252

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at java.base/java.lang.String.lookupCharset(Unknown Source) ~[na:na]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at java.base/java.lang.String.<init>(Unknown Source) ~[na:na]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at java.base/java.lang.String.<init>(Unknown Source) ~[na:na]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.support.converter.AbstractJackson2MessageConverter.convertBytesToObject(AbstractJackson2MessageConverter.java:427) ~[spring-amqp-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.support.converter.AbstractJackson2MessageConverter.convertContent(AbstractJackson2MessageConverter.java:395) ~[spring-amqp-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.support.converter.AbstractJackson2MessageConverter.doFromMessage(AbstractJackson2MessageConverter.java:364) ~[spring-amqp-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.452+05:30 [APP/PROC/WEB/0] [OUT] ... 22 common frames omitted

2023-08-23T16:18:42.581+05:30 [APP/PROC/WEB/0] [OUT] 2023-08-23T10:48:42.581Z WARN 7 --- [rmonyconsumer-1] ingErrorHandler$DefaultExceptionStrategy : Fatal message conversion error; message rejected; it will be dropped or routed to a dead letter exchange, if so configured: (Body:'[B@5a081880(byte[4100])' MessageProperties [headers={}, contentEncoding=1252, contentLength=0, receivedDeliveryMode=PERSISTENT, redelivered=false, receivedExchange=EX.HAR.PRODUCT_3PP.TOPIC, receivedRoutingKey=product.item, deliveryTag=1, consumerTag=amq.ctag-OjsC5FFDQ6_A9NPKEhNtCw, consumerQueue=Q.HMY.SKU_ITEM.PIM])

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] 2023-08-23T10:48:42.581Z ERROR 7 --- [rmonyconsumer-1] o.s.a.r.l.SimpleMessageListenerContainer : Execution of Rabbit message listener failed, and the error handler threw an exception

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] org.springframework.amqp.AmqpRejectAndDontRequeueException: Error Handler converted exception to fatal

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.ConditionalRejectingErrorHandler.handleError(ConditionalRejectingErrorHandler.java:147) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeErrorHandler(AbstractMessageListenerContainer.java:1450) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.handleListenerException(AbstractMessageListenerContainer.java:1748) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListenerAndHandleException(AbstractMessageListenerContainer.java:1524) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.lambda$executeListener$8(AbstractMessageListenerContainer.java:1481) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at io.micrometer.observation.Observation.lambda$observe$0(Observation.java:493) ~[micrometer-observation-1.11.2.jar:1.11.2]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at io.micrometer.observation.Observation.observeWithContext(Observation.java:603) ~[micrometer-observation-1.11.2.jar:1.11.2]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at io.micrometer.observation.Observation.observe(Observation.java:492) ~[micrometer-observation-1.11.2.jar:1.11.2]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1481) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:994) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:941) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1323) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1225) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] Caused by: org.springframework.amqp.rabbit.support.ListenerExecutionFailedException: Failed to convert message

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:158) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1660) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1579) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1567) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1558) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListenerAndHandleException(AbstractMessageListenerContainer.java:1503) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] ... 10 common frames omitted

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] Caused by: org.springframework.amqp.support.converter.MessageConversionException: Failed to convert Message content

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.support.converter.AbstractJackson2MessageConverter.doFromMessage(AbstractJackson2MessageConverter.java:367) ~[spring-amqp-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.support.converter.AbstractJackson2MessageConverter.fromMessage(AbstractJackson2MessageConverter.java:321) ~[spring-amqp-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.support.converter.AbstractJackson2MessageConverter.fromMessage(AbstractJackson2MessageConverter.java:304) ~[spring-amqp-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.adapter.AbstractAdaptableMessageListener.extractMessage(AbstractAdaptableMessageListener.java:342) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter$MessagingMessageConverterAdapter.extractPayload(MessagingMessageListenerAdapter.java:385) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.support.converter.MessagingMessageConverter.fromMessage(MessagingMessageConverter.java:132) ~[spring-amqp-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.toMessagingMessage(MessagingMessageListenerAdapter.java:258) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:148) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] ... 15 common frames omitted

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] Caused by: java.io.UnsupportedEncodingException: 1252

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at java.base/java.lang.String.lookupCharset(Unknown Source) ~[na:na]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at java.base/java.lang.String.<init>(Unknown Source) ~[na:na]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at java.base/java.lang.String.<init>(Unknown Source) ~[na:na]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.support.converter.AbstractJackson2MessageConverter.convertBytesToObject(AbstractJackson2MessageConverter.java:427) ~[spring-amqp-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.support.converter.AbstractJackson2MessageConverter.convertContent(AbstractJackson2MessageConverter.java:395) ~[spring-amqp-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.support.converter.AbstractJackson2MessageConverter.doFromMessage(AbstractJackson2MessageConverter.java:364) ~[spring-amqp-3.0.6.jar:3.0.6]

2023-08-23T16:18:42.582+05:30 [APP/PROC/WEB/0] [OUT] ... 22 common frames omitted

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] 2023-08-23T10:50:31.794Z WARN 7 --- [rmonyconsumer-1] s.a.r.l.ConditionalRejectingErrorHandler : Execution of Rabbit message listener failed.

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] org.springframework.amqp.rabbit.support.ListenerExecutionFailedException: Failed to convert message

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:158) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1660) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1579) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1567) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1558) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListenerAndHandleException(AbstractMessageListenerContainer.java:1503) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.lambda$executeListener$8(AbstractMessageListenerContainer.java:1481) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] at io.micrometer.observation.Observation.lambda$observe$0(Observation.java:493) ~[micrometer-observation-1.11.2.jar:1.11.2]

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] at io.micrometer.observation.Observation.observeWithContext(Observation.java:603) ~[micrometer-observation-1.11.2.jar:1.11.2]

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] at io.micrometer.observation.Observation.observe(Observation.java:492) ~[micrometer-observation-1.11.2.jar:1.11.2]

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1481) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:994) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:941) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1323) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1225) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] Caused by: org.springframework.amqp.support.converter.MessageConversionException: Failed to convert Message content

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.support.converter.AbstractJackson2MessageConverter.doFromMessage(AbstractJackson2MessageConverter.java:367) ~[spring-amqp-3.0.6.jar:3.0.6]

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.support.converter.AbstractJackson2MessageConverter.fromMessage(AbstractJackson2MessageConverter.java:321) ~[spring-amqp-3.0.6.jar:3.0.6]

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.support.converter.AbstractJackson2MessageConverter.fromMessage(AbstractJackson2MessageConverter.java:304) ~[spring-amqp-3.0.6.jar:3.0.6]

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.adapter.AbstractAdaptableMessageListener.extractMessage(AbstractAdaptableMessageListener.java:342) ~[spring-rabbit-3.0.6.jar:3.0.6]

2023-08-23T16:20:31.796+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter$MessagingMessageConverterAdapter.extractPayload(MessagingMessageListenerAdapter.java:385) ~[spring-rabbit-3.0.6.jar:3.0.6]

**Comment by mechero** [comment]
Hi! I need to find time to update this project to work with the latest Spring Boot version.
